[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "autopath"
version = "1.0.0"
description = "Auto-correcting filesytem path creation, sanitization, unique naming, custom patchways, deep file discovery, bulk collection, and live folder watching."
requires-python = ">=3.9"
dependencies = []

[project.scripts]
autopath = "autopath.cli:main"

[tool.setuptools.packages.find]
where = ["src"]

[project.urls]
"Homepage" = "https://github.com/NRAEnterprises/autopath-package"
"Repository" = "https://github.com/NRAEnterprises/autopath-package"
